# Generated by Django 3.0.8 on 2020-08-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.URLField(blank=True, default='https://i.imgur.com/EqUd38p.png'),
        ),
    ]
