# Generated by Django 3.0.8 on 2020-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.URLField(default='https://i.imgur.com/EqUd38p.png'),
        ),
    ]
