# Generated by Django 3.0.8 on 2020-08-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200801_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(blank=True, default='https://imgur.com/odto5AG'),
        ),
    ]
