# Generated by Django 3.0.8 on 2020-08-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_newsstory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
