# Generated by Django 3.0.8 on 2020-08-09 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_auto_20200809_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='favourites',
            field=models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
