# Generated by Django 3.0.8 on 2020-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200811_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
