# Generated by Django 3.0.8 on 2020-08-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200811_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
